name: traccar_client
description: "Traccar Client"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  traccar_client_sdk: ^1.0.10
  shared_preferences: ^2.5.5
  firebase_core: ^4.9.0
  firebase_messaging: ">=16.2.2 <16.4.2"
  firebase_analytics: ^12.4.1
  firebase_crashlytics: ">=5.2.2 <5.2.5"
  quick_actions: ^1.1.0
  rate_my_app: ^2.4.1
  shared_preferences_android: ^2.4.23
  mobile_scanner: ^7.4.0
  flutter_secure_storage: ^11.0.0
  app_links: ^7.0.0
  app_settings: ^8.0.3
  share_plus: ^13.3.0
  managed_configurations: ^1.2.0
  package_info_plus: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/logo.png
    - assets/brand/techrios.png
    - assets/brand/techrios-white.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#005ABA"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  remove_alpha_ios: true
